export const MENU_ITEMS = [
  { label: "Appetizers", id: "appetizers" },
  { label: "Indian Street Chat", id: "street-chat" },
  { label: "House of Biryani & Momos", id: "biryani-momos" },
  { label: "Classic Dosa", id: "classic-dosa" },
  { label: "Signature Dosa", id: "signature-dosa" },
  { label: "Fried Rice & Noodles", id: "fried-rice-noodles" },
  { label: "Idly Vada Uttapam", id: "idly-vada-uttapam" },
  { label: "Stir Fry", id: "stir-fry" },
  { label: "Vegetarian Roti" , id : "veg-roti"},
  { label: "Vegan Roti" , id : "vegan-roti"},
  { label: "Non - Vegetarian Roti" , id : "non-veg-roti"},
  { label: "Sides ( Naan / Roti )" , id : "sides"},
  { label: "Drinks" , id : "drinks"},
  { label: "Desert" , id : "desert"},
];